name: step-ca
version: 0.28.3-1
slug: step-ca
description: >-
  step-ca is an online Certificate Authority (CA) for secure, automated X.509
  and SSH certificate management.
url: 'https://github.com/hobbypunk90/homeassistant-addons/'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 2021.11.0
startup: application
ports:
  9000/tcp: 9000
ports_description:
  9000/tcp: authority port for certificate generation
ingress: false
map:
  - 'addon_config:rw'
  - 'ssl:rw'
options:
  password: ''
  debug: false
  root_ca_path: /ssl/root_ca.crt
schema:
  password: password
  debug: bool
  root_ca_path: str
